image: node:18

stages:
  - build
  - test

cache:
  key: ${CI_COMMIT_REF_SLUG}-root
  paths:
    - node_modules/

backend_build:
  stage: build
  script:
    - cd backend
    - npm install
  artifacts:
    paths:
      - backend/node_modules/
    expire_in: 1 hour

backend_test:
  stage: test
  dependencies:
    - backend_build
  variables:
    NODE_PATH: ./backend/node_modules
  script:
    - npm install
    - npm run test:backend -- --ci --runInBand
  artifacts:
    when: always
    paths:
      - backend/coverage/
      - junit.xml
