image: node:18

stages:
  - build
  - test

cache:
  key: ${CI_COMMIT_REF_SLUG}-root
  paths:
    - node_modules/

backend_build:
  stage: build
  script:
    - cd backend
    - npm install
  artifacts:
    paths:
      - backend/node_modules/
    expire_in: 1 hour

backend_test:
  stage: test
  dependencies:
    - backend_build
  script:
    # install root deps (jest, jest-junit, supertest)
    - npm install

    # run tests from root
    - npm run test:backend -- --ci --runInBand --coverage
  artifacts:
    when: always
    reports:
      junit: junit.xml
    paths:
      - coverage/
      - junit.xml
